name: Update GitHub repos

on:
  schedule:
    - cron: "0 5 * * 1"   # Mondays 05:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-repos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Fetch repos
        env:
          GITHUB_USERNAME: "matc-thaher"   # <-- change if needed
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/update_repos.py
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add _data/repos.json
            git commit -m "chore: update GitHub repos"
            git push
          else
            echo "No changes."
          fi
