name: Update publications from Google Scholar

on:
  schedule:
    - cron: "0 3 * * 1"   # every Monday at 03:00 UTC
  workflow_dispatch:      # allow manual runs

permissions:
  contents: write

jobs:
  update-scholar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scholarly==1.7.11

      - name: Fetch Google Scholar publications
        env:
          SCHOLAR_USER_ID: ${{ secrets.SCHOLAR_USER_ID }}
        run: |
          python scripts/update_scholar.py

      - name: Commit & push changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add _data/scholar.json
            git commit -m "chore: update publications from Google Scholar"
            git push
          else
            echo "No changes."
          fi
